do not exit on error.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -125,7 +125,9 @@ chmod +w $cache_dir/out/$APP-$VERSION.tar.gz
 # determine capabilities of this slug
 # can eval run Elixir?
 output_section "Determining release capabilities"
+set +o errexit    # do not exit if there is an error
 RESULT=$(_build/${RELEASE_ENV}/rel/$APP/bin/$APP eval 'IO.inspect 123+123')
+set -o errexit    # always exit on error
 if [ $? -eq 0 ]; then
   if [ $RESULT -eq '246' ]; then
     # success. write out capabilities file. # capabilities file is gigalixir-only, heroku ignores.
